name: Run Tests on Push
on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        run: sudo apt install -y nodejs

      - name: Do Test
        run: node --test
